using HautsFramework;
using RimWorld;
using RimWorld.Planet;
using RimWorld.QuestGen;
using System.Collections.Generic;
using Verse;
using Verse.Grammar;

namespace HautsPermits
{
    /*as with Atlas, this was made before the invention of QuestNode_RoverIntermediary. It was also made before the Odyssey DLC was announced, otherwise I would've picked a different name to minimize potential confusion.
     * make a bunch of WorldObject_OdysseyPoints. Does all the mutators:
     * odyssey1: Loaded Itinerary adds LI_extraSites to the number of generated OdysseyPoints, adds LI_extraDays to the deadline, and extends the range which OdysseyPoints can be generated away from the target map by LI_maxDist tiles.
     * odyssey2: each generated OdysseyPoint has RE_chance to have its RE_points assigned to [RE_pointsFactor * storyteller's current threat points]. Up to RE_maxAmbushes OdysseyPoints can be affected in this way.
     * odyssey3: Skill Gauntlet picks a random skill and a minimum level for it (SG_levelBase, but reduced by SG_levelReductionPerExtraSite per OdysseyPoint past the minimum normal_siteCount),
     *   both of which get passed to all created OdysseyPoints. Does not count bonus OdysseyPoints generated by Loaded Itinerary*/
    public class QuestNode_Root_Odyssey : QuestNode_Sequence
    {
        protected override void RunInt()
        {
            if (BranchQuestSetupUtility.TryFindRoverFaction(out Faction roverFaction))
            {
                Slate slate = QuestGen.slate;
                Quest quest = QuestGen.quest;
                PlanetTile tile = QuestSetupUtility.Quest_TryGetPlanetTile();
                Map map = QuestSetupUtility.Quest_TryGetMap();
                int numSites = this.normal_siteCount.RandomInRange;
                int timeout = (numSites - 1) * this.ticksPerSite;
                int maxDist = 20;
                bool SG_on = BranchQuestSetupUtility.MutatorEnabled(HVMP_Mod.settings.odyssey3, HVMP_Mod.settings.odysseyX);
                int SG_minSkillLevel = this.SG_levelBase - (this.SG_levelReductionPerExtraSite * (numSites - this.normal_siteCount.min));
                SkillDef SG_sd = DefDatabase<SkillDef>.GetRandom();
                if (SG_on)
                {
                    slate.Set<int>("SG_levelDesc", SG_minSkillLevel, false);
                    slate.Set<string>("SG_nameDesc", SG_sd.label.CapitalizeFirst(), false);
                    QuestGen.AddQuestDescriptionRules(new List<Rule>
                    {
                        new Rule_String("mutator_SG_info", this.SG_description.Formatted())
                    });
                } else {
                    QuestGen.AddQuestDescriptionRules(new List<Rule> { new Rule_String("mutator_SG_info", " ") });
                }
                bool LI_on = BranchQuestSetupUtility.MutatorEnabled(HVMP_Mod.settings.odyssey1, HVMP_Mod.settings.odysseyX);
                if (LI_on)
                {
                    numSites += this.LI_extraSites;
                    timeout += this.LI_extraDays;
                    maxDist = this.LI_maxDist;
                }
                bool RE_on = BranchQuestSetupUtility.MutatorEnabled(HVMP_Mod.settings.odyssey2, HVMP_Mod.settings.odysseyX);
                int RE_ambushLimit = this.RE_maxAmbushes;
                if (RE_on)
                {
                    QuestGen.AddQuestDescriptionRules(new List<Rule>
                    {
                        new Rule_String("mutator_RE_info", this.RE_description.Formatted())
                    });
                } else {
                    QuestGen.AddQuestDescriptionRules(new List<Rule> { new Rule_String("mutator_RE_info", " ") });
                }
                List<WorldObject> wos = new List<WorldObject>();
                for (int i = 0; i < numSites; i++)
                {
                    if (this.TryFindSiteTile(tile, out PlanetTile num, maxDist))
                    {
                        WorldObject_OdysseyPoint wo = (WorldObject_OdysseyPoint)WorldObjectMaker.MakeWorldObject(HVMPDefOf.HVMP_OdysseyPoint);
                        wo.Tile = num;
                        wo.SetFaction(roverFaction);
                        //wo.GetComponent<TimeoutComp>().StartTimeout((numSites - 1) * this.ticksPerSite);
                        quest.SpawnWorldObject(wo, null, null);
                        QuestUtility.AddQuestTag(ref wo.questTags, this.storeSitesAs.GetValue(slate));
                        wo.linkedQuest = quest;
                        if (RE_on && RE_ambushLimit > 0 && Rand.Chance(this.RE_chance))
                        {
                            wo.RE_points = (int)(this.RE_pointsFactor * StorytellerUtility.DefaultThreatPointsNow(map));
                            RE_ambushLimit--;
                        }
                        if (SG_on && SG_sd != null)
                        {
                            wo.SG_level = SG_minSkillLevel;
                            wo.SG_skill = SG_sd;
                        }
                        quest.WorldObjectTimeout(wo, timeout, null, null, false, null, true);
                        wos.Add(wo);
                    }
                }
                slate.Set<List<WorldObject>>("worldObject", wos, false);
                slate.Set<Map>("map", map, false);
                slate.Set<int>("numSites", numSites, false);
                slate.Set<int>("timeoutDays", timeout / 60000, false);
                slate.Set<int>("timeout", timeout, false);
                slate.Set<Faction>("faction", roverFaction, false);
                BranchQuestSetupUtility.SetSettingScalingRewardValue(slate);
            }
            base.RunInt();
        }
        private bool TryFindSiteTile(PlanetTile pTile, out PlanetTile tile, int maxDist)
        {
            return TileFinder.TryFindNewSiteTile(out tile, pTile, 2, maxDist, false, DefDatabase<LandmarkDef>.AllDefsListForReading, 0.5f, true, TileFinderMode.Near, true, false, null, null);
        }
        protected override bool TestRunInt(Slate slate)
        {
            BranchQuestSetupUtility.SetSettingScalingRewardValue(slate);
            Map map = QuestSetupUtility.Quest_TryGetMap();
            PlanetTile pTile = QuestSetupUtility.Quest_TryGetPlanetTile();
            return this.TryFindSiteTile(pTile, out PlanetTile num, 20) && BranchQuestSetupUtility.TryFindRoverFaction(out Faction roverFaction) && base.TestRunInt(slate);
        }
        [NoTranslate]
        public SlateRef<string> storeSitesAs;
        [NoTranslate]
        public SlateRef<string> inSignal;
        public int ticksPerSite;
        public IntRange normal_siteCount;
        public int normal_maxDist;
        public int LI_extraSites;
        public int LI_extraDays;
        public int LI_maxDist;
        public float RE_chance;
        public int RE_maxAmbushes;
        public float RE_pointsFactor;
        [MustTranslate]
        public string RE_description;
        public int SG_levelBase;
        public int SG_levelReductionPerExtraSite;
        [MustTranslate]
        public string SG_description;
        [NoTranslate]
        public SlateRef<string> SG_storeLevelAs;
        [NoTranslate]
        public SlateRef<string> SG_storeSkillAs;
    }
    /*visit this point to destroy it (but in a good way; you want to destroy all of them in this way to succeed on the quest).
     * Visitation doesn't count if no visiting pawn has at least SG_level in SG_skill - these are assigned by the quest node for the Skill Gauntlet mutator, as mentioned above.
     * You will be ambushed on visiting this point, if RE_points is > 0. Also assigned by quest node, as mentioned above.*/
    public class WorldObject_OdysseyPoint : WorldObject
    {
        public override IEnumerable<FloatMenuOption> GetFloatMenuOptions(Caravan caravan)
        {
            foreach (FloatMenuOption o in base.GetFloatMenuOptions(caravan))
            {
                yield return o;
            }
            foreach (FloatMenuOption f in CaravanArrivalAction_VisitOdysseyPoint.GetFloatMenuOptions(caravan, this))
            {
                yield return f;
            }
            yield break;
        }
        public string OutSignalCompleted
        {
            get
            {
                return string.Concat(new object[]
                {
                    "Quest",
                    this.linkedQuest.id,
                    ".allSites.Finished"
                });
            }
        }
        public override string GetInspectString()
        {
            string text = base.GetInspectString();
            if (this.SG_skill != null)
            {
                text += "HVMP_OdysseySiteLabel_SG".Translate(this.SG_level, this.SG_skill.label.CapitalizeFirst());
            }
            return text;
        }
        public void Notify_CaravanArrived(Caravan caravan)
        {
            if (this.SG_skill != null)
            {
                bool skillLevelMet = false;
                foreach (Pawn p in caravan.pawns)
                {
                    if (p.skills != null)
                    {
                        SkillRecord sr = p.skills.GetSkill(this.SG_skill);
                        if (sr != null && !sr.TotallyDisabled && sr.Level >= this.SG_level)
                        {
                            skillLevelMet = true;
                            break;
                        }
                    }
                }
                if (!skillLevelMet)
                {
                    return;
                }
            }
            this.Destroy();
            bool endQuest = true;
            if (this.RE_points > 0)
            {
                this.Ambush(caravan);
            }
            foreach (WorldObject wo in Find.WorldObjects.AllWorldObjects)
            {
                if (wo != this && wo is WorldObject_OdysseyPoint woop && woop.linkedQuest == this.linkedQuest)
                {
                    endQuest = false;
                    break;
                }
            }
            foreach (QuestPart qp in this.linkedQuest.PartsListForReading)
            {
                if (qp is QuestPart_DestroySite qpds && qpds.worldObjects.Contains(this))
                {
                    qpds.worldObjects.Remove(this);
                }
            }
            if (endQuest)
            {
                SignalArgs signalargs = default(SignalArgs);
                Find.SignalManager.SendSignal(new Signal(this.OutSignalCompleted, signalargs, false));
            }
        }
        public void Ambush(Caravan target)
        {
			BranchQuestSetupUtility.DoAmbush(target, this.RE_points);
            this.RE_points = -1;
        }
        public override void ExposeData()
        {
            base.ExposeData();
            Scribe_References.Look<Quest>(ref this.linkedQuest, "linkedQuest", false);
            Scribe_Values.Look<int>(ref this.RE_points, "RE_points", -1, false);
            Scribe_Values.Look<int>(ref this.SG_level, "SG_level", 10, false);
            Scribe_Defs.Look<SkillDef>(ref this.SG_skill, "SG_skill");
        }
        public Quest linkedQuest;
        public int RE_points;
        public int SG_level;
        public SkillDef SG_skill;
    }
    public class CaravanArrivalAction_VisitOdysseyPoint : CaravanArrivalAction
    {
        public override string Label
        {
            get
            {
                return "VisitPeaceTalks".Translate(this.odysseyPoint.Label);
            }
        }
        public override string ReportString
        {
            get
            {
                return "CaravanVisiting".Translate(this.odysseyPoint.Label);
            }
        }
        public static FloatMenuAcceptanceReport CanVisit(Caravan caravan, WorldObject_OdysseyPoint odysseyPoint)
        {
            return odysseyPoint != null && odysseyPoint.Spawned;
        }
        public CaravanArrivalAction_VisitOdysseyPoint()
        {
        }
        public CaravanArrivalAction_VisitOdysseyPoint(WorldObject_OdysseyPoint odysseyPoint)
        {
            this.odysseyPoint = odysseyPoint;
        }
        public override FloatMenuAcceptanceReport StillValid(Caravan caravan, PlanetTile destinationTile)
        {
            FloatMenuAcceptanceReport floatMenuAcceptanceReport = base.StillValid(caravan, destinationTile);
            if (floatMenuAcceptanceReport)
            {
                if (this.odysseyPoint != null && this.odysseyPoint.Tile != destinationTile)
                {
                    floatMenuAcceptanceReport = false;
                }
                else
                {
                    floatMenuAcceptanceReport = CaravanArrivalAction_VisitOdysseyPoint.CanVisit(caravan, this.odysseyPoint);
                }
            }
            return floatMenuAcceptanceReport;
        }
        public override void Arrived(Caravan caravan)
        {
            this.odysseyPoint.Notify_CaravanArrived(caravan);
        }
        public override void ExposeData()
        {
            base.ExposeData();
            Scribe_References.Look<WorldObject_OdysseyPoint>(ref this.odysseyPoint, "odysseyPoint", false);
        }
        public static IEnumerable<FloatMenuOption> GetFloatMenuOptions(Caravan caravan, WorldObject_OdysseyPoint odysseyPoint)
        {
            return CaravanArrivalActionUtility.GetFloatMenuOptions<CaravanArrivalAction_VisitOdysseyPoint>(() => CaravanArrivalAction_VisitOdysseyPoint.CanVisit(caravan, odysseyPoint), () => new CaravanArrivalAction_VisitOdysseyPoint(odysseyPoint), "VisitPeaceTalks".Translate(odysseyPoint.Label), caravan, odysseyPoint.Tile, odysseyPoint, null);
        }
        private WorldObject_OdysseyPoint odysseyPoint;
    }
}
